version: '3'
services:
  amqp_server:
    build: ./server
    environment:
    - webserver_port=3001
    - AMQP_URL=rabbitmq:5672
    ports:
    - "3001:8080"
    depends_on:
    - "rabbitmq"
    command: npm start

  amqp_clientservice:
    build: ./client
    environment:
    - AMQP_URL=rabbitmq:5672
    depends_on:
    - "rabbitmq"
    - "amqp_server"
    command: npm start

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
     - "5672:5672"